name: R-CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  R-CI:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install R dependencies
      run: |
        Rscript -e 'install.packages(c("devtools", "usethis", "pkgdown", "rcmdcheck", "rversions", "urlchecker", "remotes"), repos = "https://cloud.r-project.org")'
        Rscript -e 'remotes::install_deps(dependencies = TRUE)'

    - name: Check R package
      run: R CMD check --no-manual .
