name: R-CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  R-CI:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies
      run: |
        Rscript -e 'options(repos = c(CRAN = "https://cloud.r-project.org")); install.packages(c("devtools", "usethis", "pkgdown", "rcmdcheck", "rversions", "urlchecker"))'
        Rscript -e 'devtools::install_deps(dependencies = TRUE)'

    - name: Check R package
      run: R CMD check .
