name: R-CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  R-CI:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Set up R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: rmarkdown

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcurl4-openssl-dev \
          libssl-dev \
          libxml2-dev \
          libharfbuzz-dev \
          libfribidi-dev \
          libfontconfig1-dev \
          libfreetype6-dev \
          libpng-dev

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install R dependencies
      run: |
        Rscript -e 'install.packages(c("ragg", "textshaping", "pkgdown"), repos = "https://cloud.r-project.org")'
        Rscript -e 'install.packages(c("devtools", "usethis", "rcmdcheck", "rversions", "urlchecker", "remotes", "bench"), repos = "https://cloud.r-project.org")'
        Rscript -e 'remotes::install_deps(dependencies = TRUE)'


    - name: Pre-load devtools
      run: Rscript -e 'library(devtools)'

    - name: Build vignettes
      run: Rscript -e "devtools::build_vignettes()"

    - name: Check R package
      run: R CMD check --no-manual .
